# Dependencies
markdown:         redcarpet
highlighter:      pygments
gems: [jekyll-paginate, jekyll-gist]


# Permalinks
permalink:        pretty

# Setup
title:            Gabriel Clermont
tagline:          'Yup'
description:      'Filmmaker, man, friend'
url:              http://www.gabrielclermont.com/
baseurl:          ""

author:
  name:           'Gabriel Clermont'
  url:            https://twitter.com/gabrieltrane

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/gabrielclermont/gabrielclermont.com
