# Dependencies
markdown:         redcarpet
highlighter:      pygments
gems: [jekyll-paginate, jekyll-gist]


# Permalinks
permalink:        pretty

# Setup
title:            Gabriel Clermont
tagline:          'Artist?'
description:      'The personal website of filmmaker and writer Gabriel Clermont'
url:              http://www.gabrielclermont.com/
baseurl:          ""

author:
  name:           'Gabriel Clermont'
  url:            https://twitter.com/gabrieltrane

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/gabrielclermont/gabrielclermont.com
